apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langflow-service
  namespace: langflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: langflow.64bit.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: langflow-service-backend
            port:
              number: 7860
